config/routes.rb
Rails.application.routes.draw do

  root   'home_page#home'
  
  get    '/signup'        , to: 'users#new'
  post   '/signup'        , to: 'users#create'
  get    '/users'         , to: 'users#index'
  get    '/users/:id'     , to: 'users#show'
  get    '/users/:id/edit', to: 'users#edit'
  post   '/users/:id'     , to: 'users#update'
  delete '/users/:id'     , to: 'users#destroy'

  get    '/login'         , to: 'sessions#new'
  post   '/login'         , to: 'sessions#create'
  delete '/logout'        , to: 'sessions#destroy'

  resources :users
  resources :comments
  resources :posts

end

app/models/user.rb
class User < ApplicationRecord

    attr_accessor :remember_token

    has_many :posts   , dependent: :destroy
    has_many :comments, dependent: :destroy

    before_create { email.downcase! }
    has_secure_password

    validates :name, presence: true, length: { minimum: 2, maximum: 50 }, 
                                    uniqueness: { case_sensitive: true }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, 
                                        format: { with: VALID_EMAIL_REGEX }

    validates :password, presence: true, length: { minimum: 6, maximum: 100 }

    class << self

        def digest(string)
            cost = ActiveModel::SecurePassword.min_cost ? 
                        BCrypt::Engine::MIN_COST : BCrypt::Engine.cost                                                          
            BCrypt::Password.create(string, cost: cost)
        end

        def new_token
            SecureRandom.urlsafe_base64
        end

    end

    def remember
        @remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(@remember_token))
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user    , only: [:show, :edit, 
                                            :update, :destroy]
  before_action :user_params , only: [:create, :update]
  before_action :check_login , only: [:show, :edit, :update, 
                                             :destroy, :index]
  before_action :admin_auth  , only: [:delete]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account created successfully."
      log_in @user
      redirect_to @user
    else
      flash[:error] = "Failed to create account."
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Account edited successfully."
      redirect_to @user 
    else
      flash[:error] = "Failed to edit account."
      redirect_to root_path
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Selected account successfully deleted."
      redirect_to users_path
    else
      flash[:error] = "Failed to delete."
      redirect_to users_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def admin_auth
    redirect_to(root_url) unless current_user.admin?
  end

  def correct_user
    redirect_to(root_url) unless User.find(current_user.id) == User.find(params[:id])
  end

  def check_login
    redirect_to(root_url) unless logged_in?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= form_for(@user) do |f| %>
    <%= render 'form', f: f %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
    <% @users.each do |user| %>
        <li>
            <%= user.name %>
            <% if user.online? %>
                - <%= "online" %>
            <% end %>
            <% if current_user.admin? && current_user != user %>
                <%= link_to 'delete', user, method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
        </li>
                <%= "*" * 50 %>
    <% end %>
</ul>

<%= link_to 'Return to home page', root_path %>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'form', f: f %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %> | Profile</h1>
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<%= @user.created_at %> | <%= @user.updated_at %>

<% if User.find(current_user.id) == User.find(params[:id]) %>
    <%= link_to 'Edit', edit_user_path(@user) %> - <%= link_to 'Create a new post', new_post_path %> | 
                                                   <%= link_to 'Return to home page', root_path %>
<% else %>
    <%= link_to 'Return home page', root_path %>
<% end %>