config/routes.rb
Rails.application.routes.draw do

  root   'home_page#home'
  
  get    '/signup'        , to: 'users#new'
  post   '/signup'        , to: 'users#create'
  get    '/users'         , to: 'users#index'
  get    '/users/:id'     , to: 'users#show'
  get    '/users/:id/edit', to: 'users#edit'
  post   '/users/:id'     , to: 'users#update'
  delete '/users/:id'     , to: 'users#destroy'

  get    '/login'         , to: 'sessions#new'
  post   '/login'         , to: 'sessions#create'
  delete '/logout'        , to: 'sessions#destroy'

  resources :users
  resources :comments
  resources :posts

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many   :comments, dependent: :destroy

  validates  :content, presence: true, length: { maximum: 50 }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :edit_auth_check, only: [:edit, :update]
  before_action :del_auth_check , only: [:destroy]
  before_action :set_post       , only: [:show]

  def new
    @post = current_user.posts.build
  end

  def create
    redirect_to(root_url) unless logged_in?
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post sended."
      redirect_to @post
    else
      flash[:error] = "Failed to send post."
      render :new
    end
  end

  def show
    @comments = @post.comments.all 
    @comment  = current_user.comments.build if logged_in?
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = "Post edited."
      redirect_to @post
    else
      flash[:error] = "Failed to edit post."
      redirect_to :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Post deleted."
      redirect_to root_path
    else
      flash[:error] = "Failed to delete post."
      redirect_to @post
    end
  end

  private

  def edit_auth_check
    set_post
    redirect_to(root_url) unless logged_in? && current_user == User.find(@post.user_id)
  end

  def del_auth_check
    set_post
    redirect_to(root_url) unless logged_in? && (current_user.admin? || 
                                                current_user == User.find(@post.user_id))
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= f.label :title %>

<hr />

<%= f.text_field :title %>

<hr />

<%= f.label :content %>

<hr />

<%= f.text_area :content %>

<hr />

<%= f.submit %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for(@post) do |f| %>
    <%= render "form" , f: f %>
<% end %>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<%= form_for(@post) do |f| %>
    <%= render "form" , f: f %>
<% end %>

app/views/posts/show.html.erb
<section id="post">
    <h1 id="post-title"><%= @post.title %></h1>
    <span class="user-name"><i>Posted by <%= @post.user.name %>. </i></span>
    <h4 id="post-content"><%= @post.content %></h4>

    <i class="post-create-date">Created at: </i><%= @post.created_at%>

    <% if @post.updated_at > @post.created_at %>
        <i class="post-update-date">Updated at: </i><%= @post.updated_at %>
    <% end %>

    <% if @post.user == current_user || current_user.admin? %>
        <%= link_to 'Delete', @post, method: :delete, data: { confirm: "Are you sure?" } %>
        <% if @post.user == current_user %>
            <%= link_to 'Edit', edit_post_path(@post) %>
        <% end %>
    <% end %>
</section>

<% if logged_in? %>
    <section id="new-comment">
        <%= render "shared/comment-form", id_post: params[:id] %>
    </section>
<% end %>

<section id="comments">
    <ol>
        <% @comments.each do |comment| %>
            <li>
                <span class="user-name"><i><%= comment.user.name %> says: </i></span>
                <span class="comment-content"><%= comment.content %></span>
                <i class="comment-create-date">Created at: </i><%= comment.created_at%>

                <% if comment.updated_at > comment.created_at %>
                    <i class="comment-update-date">Updated at: </i><%= comment.updated_at %>
                <% end %>

                <% if comment.user == current_user || current_user.admin? %>
                    <%= link_to 'Delete', comment, method: :delete, data: { confirm: "Are you sure?" } %>
                    <% if comment.user == current_user %>
                        <%= link_to 'Edit', edit_comment_path(comment) %>
                    <% end %>
                <% end %>
            </li>
        <% end %>
    </ol>
</section>